### ISSUE TITLE
Missing list.txt

### ISSUE THREAD

**Issue by Shahnawazgrewal** [johnarevalo/gmu-mmimdb#2]
Can you please include `list.txt `or the format of the file

**Comment by johnarevalo** [comment]
Each line in this file contains the path to the json files contained in the [raw dataset](http://lisi1.unal.edu.co/mmimdb/mmimdb.tar.gz). If you extracted it in the same path of this project, you can build the `list.txt` with 

```bash
ls dataset/*.json > list.txt
```

the file would contain:

```
dataset/0000008.json
dataset/0000010.json
dataset/0000192.json
dataset/0000439.json
dataset/0000942.json
dataset/0002381.json
dataset/0003014.json
dataset/0003419.json
dataset/0003740.json
dataset/0003772.json
dataset/0004008.json
...
```

**Comment by sgasse** [comment]
I stumbled over the same issue. You could maybe include that information in the section on how to build the dataset.
