### ISSUE TITLE
MM-IMDB download links broken

### ISSUE THREAD

**Issue by Richarizardd** [johnarevalo/gmu-mmimdb#3]
Links for downloading mm-imdb are broken.

http://lisi1.unal.edu.co/mmimdb/mmimdb.tar.gz
http://lisi1.unal.edu.co/mmimdb/metadata.npy
http://lisi1.unal.edu.co/mmimdb/multimodal_imdb.hdf5

Is there a way to repair these links and/or alternative way to download this data?

**Comment by johnarevalo** [comment]
Server is under maintenance, it will be back online next week. Sorry for the inconvenience.

**Comment by johnarevalo** [comment]
you can try this url meanwhile http://168.176.36.11/mmimdb/

**Comment by Richarizardd** [comment]
Works perfectly - thank you!

**Comment by johnarevalo** [comment]
Server is now back online.

**Comment by JosephKJ** [comment]
The server seems to be down now. http://168.176.36.11/mmimdb/ also doesnt work.

**Comment by johnarevalo** [comment]
You can find a mirror copy in kaggle:

https://www.kaggle.com/johnarevalo/datasets
