### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by douwekiela** [johnarevalo/gmu-mmimdb#4]
Hi John,

It appears that the MM-IMDb dataset link (http://lisi1.unal.edu.co/mmimdb/mmimdb.tar.gz) is dead? Do you have a backup somewhere for the public?

Thanks

**Comment by johnarevalo** [comment]
Hi, sorry about it. There is a copy in kaggle:

raw copy : https://www.kaggle.com/johnarevalo/raw-mmimdb
fuel preprocessed version: https://www.kaggle.com/johnarevalo/mmimdb

**Comment by douwekiela** [comment]
Ah yeah we found that one.. There is no location that does not require a login? That would make it easier for us to open source code and say "run this script and it will download everything for you".

**Comment by johnarevalo** [comment]
The current server is unstable, so we're looking for alternatives to host the dataset. do you know any platform that provides anonymous access to ~15GB dataset?

**Comment by johnarevalo** [comment]
FWIW, I uploaded the file you mentioned in https://archive.org/download/mmimdb/mmimdb.tar.gz
