### ISSUE TITLE
negative pixel values in the dataset

### ISSUE THREAD

**Issue by WinglokWong616** [johnarevalo/gmu-mmimdb#6]
Hi! When I tried to read the posters from the _[images]_ dataset in .hdf5 file, I found negative and positive values both existing as pixels. And the array class is _int32_.

Is there a reason why there are negative pixel values? Since I want to transform them into normal 0~255, could you provide the range of the current pixel values?

Thanks

**Comment by johnarevalo** [comment]
The pretrained VGG network requires to remove the mean of the RGB channels used during training. They are also scaled and crop as implemented in the [`VGGClassifier.resize_and_crop_image`](https://github.com/johnarevalo/gmu-mmimdb/blob/95226b0d265743e7a9330549bc35b95fcb60e1dd/vgg.py#L123) function:

https://github.com/johnarevalo/gmu-mmimdb/blob/95226b0d265743e7a9330549bc35b95fcb60e1dd/vgg.py#L154-L156

You can get the original jpeg files from https://archive.org/download/mmimdb/mmimdb.tar.gz
