### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by LOTEAT** [johnarevalo/gmu-mmimdb#7]
Links for downloading mm-imdb are broken.
Is there a way to download this data?

**Comment by JackieQiang** [comment]
maybe you can find fix method at https://github.com/johnarevalo/gmu-mmimdb/issues/4

**Comment by johnarevalo** [comment]
Thanks @JackieQiang for answering. Archive links are working OK:

https://archive.org/download/mmimdb/mmimdb.tar.gz
https://archive.org/download/mmimdb/multimodal_imdb.hdf5
https://archive.org/download/mmimdb/metadata.npy

I'll close this for now. Please feel free to re-open it if they don't work for you.
